name: Target
options:
  bundleIdPrefix: com.xcodgentest
projectReferences:
  Core:
    path: ../Core/Core.xcodeproj
targets:
  Target:
    sources: Target
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    dependencies:
      - target: Core/Core
  TargetExample:
    sources: TargetExample
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    dependencies:
      - target: Target
      - target: Core/Core